version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout

      - run:
          name: Docker Compose Build
          command: docker-compose build

      - run:
          name: Run test
          command: docker-compose run -w /app app sh -c "python manage.py test"

      - run:
          name: Run flake8
          command: docker-compose run -w /app app sh -c "flake8"          

workflows:
  main:
    jobs:
      - build-and-test